version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-net

  ollama-init:
    image: curlimages/curl:latest
    container_name: ollama-init
    depends_on:
      - ollama
    entrypoint: >
      /bin/sh -c "
        echo '[ollama-init] Waiting for Ollama to be ready...';
        until curl -s http://ollama:11434/api/tags; do
          sleep 2;
        done;
        echo '[ollama-init] Ollama is up!';
        echo '[ollama-init] Pulling mxbai-embed-large model...';
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"mxbai-embed-large\"}' -H 'Content-Type: application/json';
        echo '[ollama-init] mxbai-embed-large model pull complete.';
      "
    networks:
      - app-net
    restart: "no"

  ollama-check:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    entrypoint: >
      /bin/sh -c "
        echo '[ollama-check] Verifying that mxbai-embed-large is available...';
        until curl -s http://ollama:11434/api/tags | grep '\"name\": \"mxbai-embed-large\"'; do
          echo '[ollama-check] mxbai-embed-large not found, retrying...';
          sleep 2;
        done;
        echo '[ollama-check] mxbai-embed-large is successfully loaded in Ollama.';
      "
    networks:
      - app-net
    restart: "no"

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'

volumes:
  ollama-data:

networks:
  app-net:
    driver: bridge