version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-net

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'

volumes:
  ollama-data:

networks:
  app-net:
    driver: bridge