spring:
  application:
    name: springai.ollama.basic.chat

  threads:
    virtual:
      enabled: true

  ai:
    ollama:
      chat:
        options:
          model: gemma3:1b

  docker:
    compose:
      lifecycle-management: start-only
