version: '3.9'

services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ragcontext'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    depends_on:
      - pgvector
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-net

volumes:
  ollama-data:

networks:
  app-net:
    driver: bridge