spring:
  application:
    name: springai.ollama.multimodel.image.to.text

  threads:
    virtual:
      enabled: true

  ai:
    ollama:
      chat:
        options:
          model: gemma3:4b
      init:
        pull-model-strategy: WHEN_MISSING
        embedding:
          include: false

  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down
        timeout: 1m

